[project]
name = 'Disaster-Relief-and-Aid-Distribution-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.aid-shipment-tracking]
path = 'contracts/aid-shipment-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.relief-org-registry]
path = 'contracts/relief-org-registry.clar'
clarity_version = 2
epoch = 2.5

[contracts.volunteer-management]
path = 'contracts/volunteer-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
